"""Generate the embedded C artifacts for the reduced-space NMPC controller.

Produces, in c_controller/gen/:
  kernel.c / kernel.h  -- CasADi-generated C:
      red_fgH(z, x0, ref, w) -> (f, grad, hess)   GN kernel, 3 RK4 substeps
      plant(x, u) -> x_next                       RK4 integrator, 30 substeps
  params.h             -- T1, LQR gain K, u_tilde0, X0, dimensions, bounds

Run from the Quadcopter_active_subspace_updated folder:
  ../../../../.venv-acados/bin/python c_controller/export_c_code.py
"""

from pathlib import Path
import sys

import casadi as ca
import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from Quadcopter import m, g, max_force_per_motor, nu_phy, nx  # noqa: E402
from reduced_sqp import (  # noqa: E402
    MU_MAX,
    MU_MIN,
    NV,
    NZ,
    N_horizon,
    N_stack,
    Ts,
    U_HOVER,
    U_MAX,
    U_MIN,
    X0,
    _rollout_residuals,
    make_plant,
)
from subspace_tools import (  # noqa: E402
    HorizonCost,
    TerminalFeedback,
    build_hessian_projector,
    solve_nominal_ocp,
)

GEN = HERE / "gen"
GEN.mkdir(exist_ok=True)


def build_codegen_kernel(T1):
    z = ca.SX.sym("z", NZ)
    x0 = ca.SX.sym("x0", nx)
    ref = ca.SX.sym("ref", (N_horizon + 1) * nx)
    w = ca.SX.sym("w", N_stack)
    U = ca.DM(T1) @ z[:NV] + z[NV] * w
    r = _rollout_residuals(x0, U, ref)
    Jac = ca.jacobian(r, z)
    fval = ca.dot(r, r)
    grad = 2 * Jac.T @ r
    hess = 2 * (Jac.T @ Jac)
    fval, grad, hess = ca.cse(ca.vertcat(fval)), ca.cse(grad), ca.cse(hess)
    fgH = ca.Function("red_fgH", [z, x0, ref, w], [fval, grad, hess])
    # cost-only evaluator for the Algorithm 1 fallback rule (much cheaper)
    f_only = ca.Function("red_f", [z, x0, ref, w], [fval])
    return fgH, f_only


def build_codegen_full_kernel():
    """Full single-shooting kernel: identical residuals/rollout, 40 variables."""
    U = ca.SX.sym("U", N_stack)
    x0 = ca.SX.sym("x0", nx)
    ref = ca.SX.sym("ref", (N_horizon + 1) * nx)
    r = _rollout_residuals(x0, U, ref)
    Jac = ca.jacobian(r, U)
    fval = ca.dot(r, r)
    grad = 2 * Jac.T @ r
    hess = 2 * (Jac.T @ Jac)
    fval, grad, hess = ca.cse(ca.vertcat(fval)), ca.cse(grad), ca.cse(hess)
    return ca.Function("full_fgH", [U, x0, ref], [fval, grad, hess])


def c_array(name, arr, fmt="%.17g"):
    flat = np.asarray(arr, dtype=float).reshape(-1)
    vals = ",\n    ".join(", ".join(fmt % v for v in flat[i:i + 4]) for i in range(0, len(flat), 4))
    return f"static const double {name}[{len(flat)}] = {{\n    {vals}\n}};\n"


def main():
    hc = HorizonCost(N_horizon, Ts)
    T1, T2 = build_hessian_projector(hc.fun, N_horizon, Ts, NV, X0)
    tfb = TerminalFeedback(Ts, U_MIN, U_MAX)
    # Algorithm 1, line 1 executed at export time: the embedded controller
    # ships with u~_0 = argmin of the nominal P(x0), not an arbitrary stack.
    u_tilde0 = solve_nominal_ocp(hc.fun, X0, 0.0, N_horizon, Ts, U_MIN, U_MAX)

    kernel, f_only = build_codegen_kernel(T1)
    plant = make_plant()

    cg = ca.CodeGenerator("kernel.c", {"with_header": True, "casadi_real": "double"})
    cg.add(kernel)
    cg.add(f_only)
    cg.add(plant)
    cg.generate(str(GEN) + "/")

    # full-NMPC kernel in its own translation unit (it is much larger)
    cg_full = ca.CodeGenerator("kernel_full.c", {"with_header": True, "casadi_real": "double"})
    cg_full.add(build_codegen_full_kernel())
    cg_full.generate(str(GEN) + "/")

    # params.h ---------------------------------------------------------------
    # T1 row-major (40 x 10); K row-major (4 x 12); err-state index set baked
    # into the C controller.
    lines = [
        "/* Auto-generated by export_c_code.py -- do not edit. */",
        "#ifndef AS_NMPC_PARAMS_H",
        "#define AS_NMPC_PARAMS_H",
        "",
        f"#define AS_NX {nx}",
        f"#define AS_NU {nu_phy}",
        f"#define AS_NV {NV}",
        f"#define AS_NZ {NZ}",
        f"#define AS_N {N_horizon}",
        f"#define AS_NSTACK {N_stack}",
        f"#define AS_TS {Ts!r}",
        f"#define AS_U_MIN 0.0",
        f"#define AS_U_MAX {max_force_per_motor!r}",
        f"#define AS_U_HOVER {m * g / 4.0!r}",
        f"#define AS_MU_MIN {MU_MIN!r}",
        f"#define AS_MU_MAX {MU_MAX!r}",
        "",
        c_array("AS_T1", T1),                       # row-major (NSTACK x NV)
        c_array("AS_LQR_K", tfb.K),                 # row-major (NU x 12)
        c_array("AS_U_TILDE0", u_tilde0),
        c_array("AS_X0", X0),
        "#endif /* AS_NMPC_PARAMS_H */",
    ]
    (GEN / "params.h").write_text("\n".join(lines))

    # quick consistency check vs the Python kernel
    z0 = np.concatenate([T1.T @ u_tilde0, [1.0]])
    w0 = u_tilde0 - T1 @ (T1.T @ u_tilde0)
    from subspace_tools import make_reference_stack
    ref0 = make_reference_stack(0.0, N_horizon, Ts)
    f, gr, H = kernel(z0, X0, ref0, w0)
    print(f"kernel @ warm start: f = {float(f):.6f}  ||g|| = {float(ca.norm_2(gr)):.6f}")
    print(f"generated: {GEN/'kernel.c'}, {GEN/'kernel.h'}, {GEN/'params.h'}")


if __name__ == "__main__":
    main()
