/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FBL_Quadcopter_ode_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {17, 17, 1};
static const casadi_int casadi_s2[3] = {17, 4, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};

/* FBL_Quadcopter_ode_expl_vde_forw:(i0[17],i1[17x17],i2[17x4],i3[4],i4[0])->(o0[17],o1[17x17],o2[17x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][1] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a1=(a0*a1);
  a2=arg[0]? arg[0][14] : 0;
  a3=(a0*a2);
  a1=(a1+a3);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][3] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[3]? arg[3][0] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[0]? arg[0][5] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[0]? arg[0][6] : 0;
  a1=(a0*a1);
  a3=arg[0]? arg[0][15] : 0;
  a4=(a0*a3);
  a1=(a1+a4);
  if (res[0]!=0) res[0][5]=a1;
  a1=arg[0]? arg[0][7] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][6]=a1;
  a1=arg[3]? arg[3][1] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[0]? arg[0][9] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][8]=a1;
  a1=arg[0]? arg[0][10] : 0;
  a1=(a0*a1);
  a4=arg[0]? arg[0][16] : 0;
  a5=(a0*a4);
  a1=(a1+a5);
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[0]? arg[0][11] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][10]=a1;
  a1=arg[3]? arg[3][2] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][11]=a1;
  a1=arg[0]? arg[0][13] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][12]=a1;
  a1=arg[3]? arg[3][3] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a2;
  if (res[0]!=0) res[0][15]=a3;
  if (res[0]!=0) res[0][16]=a4;
  a4=arg[1]? arg[1][1] : 0;
  a4=(a0*a4);
  if (res[1]!=0) res[1][0]=a4;
  a4=arg[1]? arg[1][2] : 0;
  a4=(a0*a4);
  a3=arg[1]? arg[1][14] : 0;
  a2=(a0*a3);
  a4=(a4+a2);
  if (res[1]!=0) res[1][1]=a4;
  a4=arg[1]? arg[1][3] : 0;
  a4=(a0*a4);
  if (res[1]!=0) res[1][2]=a4;
  a4=0.;
  if (res[1]!=0) res[1][3]=a4;
  a2=arg[1]? arg[1][5] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][4]=a2;
  a2=arg[1]? arg[1][6] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][15] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][5]=a2;
  a2=arg[1]? arg[1][7] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][6]=a2;
  if (res[1]!=0) res[1][7]=a4;
  a2=arg[1]? arg[1][9] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][8]=a2;
  a2=arg[1]? arg[1][10] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][16] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][9]=a2;
  a2=arg[1]? arg[1][11] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][10]=a2;
  if (res[1]!=0) res[1][11]=a4;
  a2=arg[1]? arg[1][13] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][12]=a2;
  if (res[1]!=0) res[1][13]=a4;
  if (res[1]!=0) res[1][14]=a3;
  if (res[1]!=0) res[1][15]=a1;
  if (res[1]!=0) res[1][16]=a5;
  a5=arg[1]? arg[1][18] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][17]=a5;
  a5=arg[1]? arg[1][19] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][31] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][18]=a5;
  a5=arg[1]? arg[1][20] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][19]=a5;
  if (res[1]!=0) res[1][20]=a4;
  a5=arg[1]? arg[1][22] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][21]=a5;
  a5=arg[1]? arg[1][23] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][32] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][22]=a5;
  a5=arg[1]? arg[1][24] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][23]=a5;
  if (res[1]!=0) res[1][24]=a4;
  a5=arg[1]? arg[1][26] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][25]=a5;
  a5=arg[1]? arg[1][27] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][33] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][26]=a5;
  a5=arg[1]? arg[1][28] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][27]=a5;
  if (res[1]!=0) res[1][28]=a4;
  a5=arg[1]? arg[1][30] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][29]=a5;
  if (res[1]!=0) res[1][30]=a4;
  if (res[1]!=0) res[1][31]=a1;
  if (res[1]!=0) res[1][32]=a3;
  if (res[1]!=0) res[1][33]=a2;
  a2=arg[1]? arg[1][35] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][34]=a2;
  a2=arg[1]? arg[1][36] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][48] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][35]=a2;
  a2=arg[1]? arg[1][37] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][36]=a2;
  if (res[1]!=0) res[1][37]=a4;
  a2=arg[1]? arg[1][39] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][38]=a2;
  a2=arg[1]? arg[1][40] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][49] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][39]=a2;
  a2=arg[1]? arg[1][41] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][40]=a2;
  if (res[1]!=0) res[1][41]=a4;
  a2=arg[1]? arg[1][43] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][42]=a2;
  a2=arg[1]? arg[1][44] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][50] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][43]=a2;
  a2=arg[1]? arg[1][45] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][44]=a2;
  if (res[1]!=0) res[1][45]=a4;
  a2=arg[1]? arg[1][47] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][46]=a2;
  if (res[1]!=0) res[1][47]=a4;
  if (res[1]!=0) res[1][48]=a3;
  if (res[1]!=0) res[1][49]=a1;
  if (res[1]!=0) res[1][50]=a5;
  a5=arg[1]? arg[1][52] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][51]=a5;
  a5=arg[1]? arg[1][53] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][65] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][52]=a5;
  a5=arg[1]? arg[1][54] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][53]=a5;
  if (res[1]!=0) res[1][54]=a4;
  a5=arg[1]? arg[1][56] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][55]=a5;
  a5=arg[1]? arg[1][57] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][66] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][56]=a5;
  a5=arg[1]? arg[1][58] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][57]=a5;
  if (res[1]!=0) res[1][58]=a4;
  a5=arg[1]? arg[1][60] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][59]=a5;
  a5=arg[1]? arg[1][61] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][67] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][60]=a5;
  a5=arg[1]? arg[1][62] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][61]=a5;
  if (res[1]!=0) res[1][62]=a4;
  a5=arg[1]? arg[1][64] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][63]=a5;
  if (res[1]!=0) res[1][64]=a4;
  if (res[1]!=0) res[1][65]=a1;
  if (res[1]!=0) res[1][66]=a3;
  if (res[1]!=0) res[1][67]=a2;
  a2=arg[1]? arg[1][69] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][68]=a2;
  a2=arg[1]? arg[1][70] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][82] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][69]=a2;
  a2=arg[1]? arg[1][71] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][70]=a2;
  if (res[1]!=0) res[1][71]=a4;
  a2=arg[1]? arg[1][73] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][72]=a2;
  a2=arg[1]? arg[1][74] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][83] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][73]=a2;
  a2=arg[1]? arg[1][75] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][74]=a2;
  if (res[1]!=0) res[1][75]=a4;
  a2=arg[1]? arg[1][77] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][76]=a2;
  a2=arg[1]? arg[1][78] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][84] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][77]=a2;
  a2=arg[1]? arg[1][79] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][78]=a2;
  if (res[1]!=0) res[1][79]=a4;
  a2=arg[1]? arg[1][81] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][80]=a2;
  if (res[1]!=0) res[1][81]=a4;
  if (res[1]!=0) res[1][82]=a3;
  if (res[1]!=0) res[1][83]=a1;
  if (res[1]!=0) res[1][84]=a5;
  a5=arg[1]? arg[1][86] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][85]=a5;
  a5=arg[1]? arg[1][87] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][99] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][86]=a5;
  a5=arg[1]? arg[1][88] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][87]=a5;
  if (res[1]!=0) res[1][88]=a4;
  a5=arg[1]? arg[1][90] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][89]=a5;
  a5=arg[1]? arg[1][91] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][100] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][90]=a5;
  a5=arg[1]? arg[1][92] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][91]=a5;
  if (res[1]!=0) res[1][92]=a4;
  a5=arg[1]? arg[1][94] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][93]=a5;
  a5=arg[1]? arg[1][95] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][101] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][94]=a5;
  a5=arg[1]? arg[1][96] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][95]=a5;
  if (res[1]!=0) res[1][96]=a4;
  a5=arg[1]? arg[1][98] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][97]=a5;
  if (res[1]!=0) res[1][98]=a4;
  if (res[1]!=0) res[1][99]=a1;
  if (res[1]!=0) res[1][100]=a3;
  if (res[1]!=0) res[1][101]=a2;
  a2=arg[1]? arg[1][103] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][102]=a2;
  a2=arg[1]? arg[1][104] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][116] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][103]=a2;
  a2=arg[1]? arg[1][105] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][104]=a2;
  if (res[1]!=0) res[1][105]=a4;
  a2=arg[1]? arg[1][107] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][106]=a2;
  a2=arg[1]? arg[1][108] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][117] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][107]=a2;
  a2=arg[1]? arg[1][109] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][108]=a2;
  if (res[1]!=0) res[1][109]=a4;
  a2=arg[1]? arg[1][111] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][110]=a2;
  a2=arg[1]? arg[1][112] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][118] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][111]=a2;
  a2=arg[1]? arg[1][113] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][112]=a2;
  if (res[1]!=0) res[1][113]=a4;
  a2=arg[1]? arg[1][115] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][114]=a2;
  if (res[1]!=0) res[1][115]=a4;
  if (res[1]!=0) res[1][116]=a3;
  if (res[1]!=0) res[1][117]=a1;
  if (res[1]!=0) res[1][118]=a5;
  a5=arg[1]? arg[1][120] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][119]=a5;
  a5=arg[1]? arg[1][121] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][133] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][120]=a5;
  a5=arg[1]? arg[1][122] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][121]=a5;
  if (res[1]!=0) res[1][122]=a4;
  a5=arg[1]? arg[1][124] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][123]=a5;
  a5=arg[1]? arg[1][125] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][134] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][124]=a5;
  a5=arg[1]? arg[1][126] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][125]=a5;
  if (res[1]!=0) res[1][126]=a4;
  a5=arg[1]? arg[1][128] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][127]=a5;
  a5=arg[1]? arg[1][129] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][135] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][128]=a5;
  a5=arg[1]? arg[1][130] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][129]=a5;
  if (res[1]!=0) res[1][130]=a4;
  a5=arg[1]? arg[1][132] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][131]=a5;
  if (res[1]!=0) res[1][132]=a4;
  if (res[1]!=0) res[1][133]=a1;
  if (res[1]!=0) res[1][134]=a3;
  if (res[1]!=0) res[1][135]=a2;
  a2=arg[1]? arg[1][137] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][136]=a2;
  a2=arg[1]? arg[1][138] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][150] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][137]=a2;
  a2=arg[1]? arg[1][139] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][138]=a2;
  if (res[1]!=0) res[1][139]=a4;
  a2=arg[1]? arg[1][141] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][140]=a2;
  a2=arg[1]? arg[1][142] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][151] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][141]=a2;
  a2=arg[1]? arg[1][143] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][142]=a2;
  if (res[1]!=0) res[1][143]=a4;
  a2=arg[1]? arg[1][145] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][144]=a2;
  a2=arg[1]? arg[1][146] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][152] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][145]=a2;
  a2=arg[1]? arg[1][147] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][146]=a2;
  if (res[1]!=0) res[1][147]=a4;
  a2=arg[1]? arg[1][149] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][148]=a2;
  if (res[1]!=0) res[1][149]=a4;
  if (res[1]!=0) res[1][150]=a3;
  if (res[1]!=0) res[1][151]=a1;
  if (res[1]!=0) res[1][152]=a5;
  a5=arg[1]? arg[1][154] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][153]=a5;
  a5=arg[1]? arg[1][155] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][167] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][154]=a5;
  a5=arg[1]? arg[1][156] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][155]=a5;
  if (res[1]!=0) res[1][156]=a4;
  a5=arg[1]? arg[1][158] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][157]=a5;
  a5=arg[1]? arg[1][159] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][168] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][158]=a5;
  a5=arg[1]? arg[1][160] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][159]=a5;
  if (res[1]!=0) res[1][160]=a4;
  a5=arg[1]? arg[1][162] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][161]=a5;
  a5=arg[1]? arg[1][163] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][169] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][162]=a5;
  a5=arg[1]? arg[1][164] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][163]=a5;
  if (res[1]!=0) res[1][164]=a4;
  a5=arg[1]? arg[1][166] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][165]=a5;
  if (res[1]!=0) res[1][166]=a4;
  if (res[1]!=0) res[1][167]=a1;
  if (res[1]!=0) res[1][168]=a3;
  if (res[1]!=0) res[1][169]=a2;
  a2=arg[1]? arg[1][171] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][170]=a2;
  a2=arg[1]? arg[1][172] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][184] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][171]=a2;
  a2=arg[1]? arg[1][173] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][172]=a2;
  if (res[1]!=0) res[1][173]=a4;
  a2=arg[1]? arg[1][175] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][174]=a2;
  a2=arg[1]? arg[1][176] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][185] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][175]=a2;
  a2=arg[1]? arg[1][177] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][176]=a2;
  if (res[1]!=0) res[1][177]=a4;
  a2=arg[1]? arg[1][179] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][178]=a2;
  a2=arg[1]? arg[1][180] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][186] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][179]=a2;
  a2=arg[1]? arg[1][181] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][180]=a2;
  if (res[1]!=0) res[1][181]=a4;
  a2=arg[1]? arg[1][183] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][182]=a2;
  if (res[1]!=0) res[1][183]=a4;
  if (res[1]!=0) res[1][184]=a3;
  if (res[1]!=0) res[1][185]=a1;
  if (res[1]!=0) res[1][186]=a5;
  a5=arg[1]? arg[1][188] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][187]=a5;
  a5=arg[1]? arg[1][189] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][201] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][188]=a5;
  a5=arg[1]? arg[1][190] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][189]=a5;
  if (res[1]!=0) res[1][190]=a4;
  a5=arg[1]? arg[1][192] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][191]=a5;
  a5=arg[1]? arg[1][193] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][202] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][192]=a5;
  a5=arg[1]? arg[1][194] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][193]=a5;
  if (res[1]!=0) res[1][194]=a4;
  a5=arg[1]? arg[1][196] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][195]=a5;
  a5=arg[1]? arg[1][197] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][203] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][196]=a5;
  a5=arg[1]? arg[1][198] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][197]=a5;
  if (res[1]!=0) res[1][198]=a4;
  a5=arg[1]? arg[1][200] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][199]=a5;
  if (res[1]!=0) res[1][200]=a4;
  if (res[1]!=0) res[1][201]=a1;
  if (res[1]!=0) res[1][202]=a3;
  if (res[1]!=0) res[1][203]=a2;
  a2=arg[1]? arg[1][205] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][204]=a2;
  a2=arg[1]? arg[1][206] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][218] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][205]=a2;
  a2=arg[1]? arg[1][207] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][206]=a2;
  if (res[1]!=0) res[1][207]=a4;
  a2=arg[1]? arg[1][209] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][208]=a2;
  a2=arg[1]? arg[1][210] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][219] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][209]=a2;
  a2=arg[1]? arg[1][211] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][210]=a2;
  if (res[1]!=0) res[1][211]=a4;
  a2=arg[1]? arg[1][213] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][212]=a2;
  a2=arg[1]? arg[1][214] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][220] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][213]=a2;
  a2=arg[1]? arg[1][215] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][214]=a2;
  if (res[1]!=0) res[1][215]=a4;
  a2=arg[1]? arg[1][217] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][216]=a2;
  if (res[1]!=0) res[1][217]=a4;
  if (res[1]!=0) res[1][218]=a3;
  if (res[1]!=0) res[1][219]=a1;
  if (res[1]!=0) res[1][220]=a5;
  a5=arg[1]? arg[1][222] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][221]=a5;
  a5=arg[1]? arg[1][223] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][235] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][222]=a5;
  a5=arg[1]? arg[1][224] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][223]=a5;
  if (res[1]!=0) res[1][224]=a4;
  a5=arg[1]? arg[1][226] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][225]=a5;
  a5=arg[1]? arg[1][227] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][236] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][226]=a5;
  a5=arg[1]? arg[1][228] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][227]=a5;
  if (res[1]!=0) res[1][228]=a4;
  a5=arg[1]? arg[1][230] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][229]=a5;
  a5=arg[1]? arg[1][231] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][237] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][230]=a5;
  a5=arg[1]? arg[1][232] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][231]=a5;
  if (res[1]!=0) res[1][232]=a4;
  a5=arg[1]? arg[1][234] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][233]=a5;
  if (res[1]!=0) res[1][234]=a4;
  if (res[1]!=0) res[1][235]=a1;
  if (res[1]!=0) res[1][236]=a3;
  if (res[1]!=0) res[1][237]=a2;
  a2=arg[1]? arg[1][239] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][238]=a2;
  a2=arg[1]? arg[1][240] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][252] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][239]=a2;
  a2=arg[1]? arg[1][241] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][240]=a2;
  if (res[1]!=0) res[1][241]=a4;
  a2=arg[1]? arg[1][243] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][242]=a2;
  a2=arg[1]? arg[1][244] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][253] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][243]=a2;
  a2=arg[1]? arg[1][245] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][244]=a2;
  if (res[1]!=0) res[1][245]=a4;
  a2=arg[1]? arg[1][247] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][246]=a2;
  a2=arg[1]? arg[1][248] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][254] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][247]=a2;
  a2=arg[1]? arg[1][249] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][248]=a2;
  if (res[1]!=0) res[1][249]=a4;
  a2=arg[1]? arg[1][251] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][250]=a2;
  if (res[1]!=0) res[1][251]=a4;
  if (res[1]!=0) res[1][252]=a3;
  if (res[1]!=0) res[1][253]=a1;
  if (res[1]!=0) res[1][254]=a5;
  a5=arg[1]? arg[1][256] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][255]=a5;
  a5=arg[1]? arg[1][257] : 0;
  a5=(a0*a5);
  a1=arg[1]? arg[1][269] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[1]!=0) res[1][256]=a5;
  a5=arg[1]? arg[1][258] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][257]=a5;
  if (res[1]!=0) res[1][258]=a4;
  a5=arg[1]? arg[1][260] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][259]=a5;
  a5=arg[1]? arg[1][261] : 0;
  a5=(a0*a5);
  a3=arg[1]? arg[1][270] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[1]!=0) res[1][260]=a5;
  a5=arg[1]? arg[1][262] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][261]=a5;
  if (res[1]!=0) res[1][262]=a4;
  a5=arg[1]? arg[1][264] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][263]=a5;
  a5=arg[1]? arg[1][265] : 0;
  a5=(a0*a5);
  a2=arg[1]? arg[1][271] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[1]!=0) res[1][264]=a5;
  a5=arg[1]? arg[1][266] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][265]=a5;
  if (res[1]!=0) res[1][266]=a4;
  a5=arg[1]? arg[1][268] : 0;
  a5=(a0*a5);
  if (res[1]!=0) res[1][267]=a5;
  if (res[1]!=0) res[1][268]=a4;
  if (res[1]!=0) res[1][269]=a1;
  if (res[1]!=0) res[1][270]=a3;
  if (res[1]!=0) res[1][271]=a2;
  a2=arg[1]? arg[1][273] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][272]=a2;
  a2=arg[1]? arg[1][274] : 0;
  a2=(a0*a2);
  a3=arg[1]? arg[1][286] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[1]!=0) res[1][273]=a2;
  a2=arg[1]? arg[1][275] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][274]=a2;
  if (res[1]!=0) res[1][275]=a4;
  a2=arg[1]? arg[1][277] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][276]=a2;
  a2=arg[1]? arg[1][278] : 0;
  a2=(a0*a2);
  a1=arg[1]? arg[1][287] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[1]!=0) res[1][277]=a2;
  a2=arg[1]? arg[1][279] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][278]=a2;
  if (res[1]!=0) res[1][279]=a4;
  a2=arg[1]? arg[1][281] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][280]=a2;
  a2=arg[1]? arg[1][282] : 0;
  a2=(a0*a2);
  a5=arg[1]? arg[1][288] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[1]!=0) res[1][281]=a2;
  a2=arg[1]? arg[1][283] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][282]=a2;
  if (res[1]!=0) res[1][283]=a4;
  a2=arg[1]? arg[1][285] : 0;
  a2=(a0*a2);
  if (res[1]!=0) res[1][284]=a2;
  if (res[1]!=0) res[1][285]=a4;
  if (res[1]!=0) res[1][286]=a3;
  if (res[1]!=0) res[1][287]=a1;
  if (res[1]!=0) res[1][288]=a5;
  a5=arg[2]? arg[2][1] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][0]=a5;
  a5=arg[2]? arg[2][2] : 0;
  a5=(a0*a5);
  a1=arg[2]? arg[2][14] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[2]!=0) res[2][1]=a5;
  a5=arg[2]? arg[2][3] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][2]=a5;
  if (res[2]!=0) res[2][3]=a0;
  a5=arg[2]? arg[2][5] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][4]=a5;
  a5=arg[2]? arg[2][6] : 0;
  a5=(a0*a5);
  a3=arg[2]? arg[2][15] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[2]!=0) res[2][5]=a5;
  a5=arg[2]? arg[2][7] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][6]=a5;
  if (res[2]!=0) res[2][7]=a4;
  a5=arg[2]? arg[2][9] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][8]=a5;
  a5=arg[2]? arg[2][10] : 0;
  a5=(a0*a5);
  a2=arg[2]? arg[2][16] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[2]!=0) res[2][9]=a5;
  a5=arg[2]? arg[2][11] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][10]=a5;
  if (res[2]!=0) res[2][11]=a4;
  a5=arg[2]? arg[2][13] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][12]=a5;
  if (res[2]!=0) res[2][13]=a4;
  if (res[2]!=0) res[2][14]=a1;
  if (res[2]!=0) res[2][15]=a3;
  if (res[2]!=0) res[2][16]=a2;
  a2=arg[2]? arg[2][18] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][17]=a2;
  a2=arg[2]? arg[2][19] : 0;
  a2=(a0*a2);
  a3=arg[2]? arg[2][31] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[2]!=0) res[2][18]=a2;
  a2=arg[2]? arg[2][20] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][19]=a2;
  if (res[2]!=0) res[2][20]=a4;
  a2=arg[2]? arg[2][22] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][21]=a2;
  a2=arg[2]? arg[2][23] : 0;
  a2=(a0*a2);
  a1=arg[2]? arg[2][32] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[2]!=0) res[2][22]=a2;
  a2=arg[2]? arg[2][24] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][23]=a2;
  if (res[2]!=0) res[2][24]=a0;
  a2=arg[2]? arg[2][26] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][25]=a2;
  a2=arg[2]? arg[2][27] : 0;
  a2=(a0*a2);
  a5=arg[2]? arg[2][33] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[2]!=0) res[2][26]=a2;
  a2=arg[2]? arg[2][28] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][27]=a2;
  if (res[2]!=0) res[2][28]=a4;
  a2=arg[2]? arg[2][30] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][29]=a2;
  if (res[2]!=0) res[2][30]=a4;
  if (res[2]!=0) res[2][31]=a3;
  if (res[2]!=0) res[2][32]=a1;
  if (res[2]!=0) res[2][33]=a5;
  a5=arg[2]? arg[2][35] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][34]=a5;
  a5=arg[2]? arg[2][36] : 0;
  a5=(a0*a5);
  a1=arg[2]? arg[2][48] : 0;
  a3=(a0*a1);
  a5=(a5+a3);
  if (res[2]!=0) res[2][35]=a5;
  a5=arg[2]? arg[2][37] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][36]=a5;
  if (res[2]!=0) res[2][37]=a4;
  a5=arg[2]? arg[2][39] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][38]=a5;
  a5=arg[2]? arg[2][40] : 0;
  a5=(a0*a5);
  a3=arg[2]? arg[2][49] : 0;
  a2=(a0*a3);
  a5=(a5+a2);
  if (res[2]!=0) res[2][39]=a5;
  a5=arg[2]? arg[2][41] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][40]=a5;
  if (res[2]!=0) res[2][41]=a4;
  a5=arg[2]? arg[2][43] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][42]=a5;
  a5=arg[2]? arg[2][44] : 0;
  a5=(a0*a5);
  a2=arg[2]? arg[2][50] : 0;
  a6=(a0*a2);
  a5=(a5+a6);
  if (res[2]!=0) res[2][43]=a5;
  a5=arg[2]? arg[2][45] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][44]=a5;
  if (res[2]!=0) res[2][45]=a0;
  a5=arg[2]? arg[2][47] : 0;
  a5=(a0*a5);
  if (res[2]!=0) res[2][46]=a5;
  if (res[2]!=0) res[2][47]=a4;
  if (res[2]!=0) res[2][48]=a1;
  if (res[2]!=0) res[2][49]=a3;
  if (res[2]!=0) res[2][50]=a2;
  a2=arg[2]? arg[2][52] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][51]=a2;
  a2=arg[2]? arg[2][53] : 0;
  a2=(a0*a2);
  a3=arg[2]? arg[2][65] : 0;
  a1=(a0*a3);
  a2=(a2+a1);
  if (res[2]!=0) res[2][52]=a2;
  a2=arg[2]? arg[2][54] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][53]=a2;
  if (res[2]!=0) res[2][54]=a4;
  a2=arg[2]? arg[2][56] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][55]=a2;
  a2=arg[2]? arg[2][57] : 0;
  a2=(a0*a2);
  a1=arg[2]? arg[2][66] : 0;
  a5=(a0*a1);
  a2=(a2+a5);
  if (res[2]!=0) res[2][56]=a2;
  a2=arg[2]? arg[2][58] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][57]=a2;
  if (res[2]!=0) res[2][58]=a4;
  a2=arg[2]? arg[2][60] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][59]=a2;
  a2=arg[2]? arg[2][61] : 0;
  a2=(a0*a2);
  a5=arg[2]? arg[2][67] : 0;
  a6=(a0*a5);
  a2=(a2+a6);
  if (res[2]!=0) res[2][60]=a2;
  a2=arg[2]? arg[2][62] : 0;
  a2=(a0*a2);
  if (res[2]!=0) res[2][61]=a2;
  if (res[2]!=0) res[2][62]=a4;
  a4=arg[2]? arg[2][64] : 0;
  a4=(a0*a4);
  if (res[2]!=0) res[2][63]=a4;
  if (res[2]!=0) res[2][64]=a0;
  if (res[2]!=0) res[2][65]=a3;
  if (res[2]!=0) res[2][66]=a1;
  if (res[2]!=0) res[2][67]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FBL_Quadcopter_ode_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int FBL_Quadcopter_ode_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real FBL_Quadcopter_ode_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FBL_Quadcopter_ode_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FBL_Quadcopter_ode_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FBL_Quadcopter_ode_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FBL_Quadcopter_ode_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
