/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FBL_Quadcopter_ode_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {14, 14, 1};
static const casadi_int casadi_s2[3] = {14, 4, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};

/* FBL_Quadcopter_ode_expl_vde_forw:(i0[14],i1[14x14],i2[14x4],i3[4],i4[0])->(o0[14],o1[14x14],o2[14x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[1]!=0) res[1][1]=a0;
  a0=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][2]=a0;
  a0=0.;
  if (res[1]!=0) res[1][3]=a0;
  a1=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][4]=a1;
  a1=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][5]=a1;
  a1=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][6]=a1;
  if (res[1]!=0) res[1][7]=a0;
  a1=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a1;
  a1=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][9]=a1;
  a1=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][10]=a1;
  if (res[1]!=0) res[1][11]=a0;
  a1=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][12]=a1;
  if (res[1]!=0) res[1][13]=a0;
  a1=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][14]=a1;
  a1=arg[1]? arg[1][16] : 0;
  if (res[1]!=0) res[1][15]=a1;
  a1=arg[1]? arg[1][17] : 0;
  if (res[1]!=0) res[1][16]=a1;
  if (res[1]!=0) res[1][17]=a0;
  a1=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][18]=a1;
  a1=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][19]=a1;
  a1=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][20]=a1;
  if (res[1]!=0) res[1][21]=a0;
  a1=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][22]=a1;
  a1=arg[1]? arg[1][24] : 0;
  if (res[1]!=0) res[1][23]=a1;
  a1=arg[1]? arg[1][25] : 0;
  if (res[1]!=0) res[1][24]=a1;
  if (res[1]!=0) res[1][25]=a0;
  a1=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][26]=a1;
  if (res[1]!=0) res[1][27]=a0;
  a1=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][28]=a1;
  a1=arg[1]? arg[1][30] : 0;
  if (res[1]!=0) res[1][29]=a1;
  a1=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][30]=a1;
  if (res[1]!=0) res[1][31]=a0;
  a1=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][32]=a1;
  a1=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][33]=a1;
  a1=arg[1]? arg[1][35] : 0;
  if (res[1]!=0) res[1][34]=a1;
  if (res[1]!=0) res[1][35]=a0;
  a1=arg[1]? arg[1][37] : 0;
  if (res[1]!=0) res[1][36]=a1;
  a1=arg[1]? arg[1][38] : 0;
  if (res[1]!=0) res[1][37]=a1;
  a1=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][38]=a1;
  if (res[1]!=0) res[1][39]=a0;
  a1=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][40]=a1;
  if (res[1]!=0) res[1][41]=a0;
  a1=arg[1]? arg[1][43] : 0;
  if (res[1]!=0) res[1][42]=a1;
  a1=arg[1]? arg[1][44] : 0;
  if (res[1]!=0) res[1][43]=a1;
  a1=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][44]=a1;
  if (res[1]!=0) res[1][45]=a0;
  a1=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][46]=a1;
  a1=arg[1]? arg[1][48] : 0;
  if (res[1]!=0) res[1][47]=a1;
  a1=arg[1]? arg[1][49] : 0;
  if (res[1]!=0) res[1][48]=a1;
  if (res[1]!=0) res[1][49]=a0;
  a1=arg[1]? arg[1][51] : 0;
  if (res[1]!=0) res[1][50]=a1;
  a1=arg[1]? arg[1][52] : 0;
  if (res[1]!=0) res[1][51]=a1;
  a1=arg[1]? arg[1][53] : 0;
  if (res[1]!=0) res[1][52]=a1;
  if (res[1]!=0) res[1][53]=a0;
  a1=arg[1]? arg[1][55] : 0;
  if (res[1]!=0) res[1][54]=a1;
  if (res[1]!=0) res[1][55]=a0;
  a1=arg[1]? arg[1][57] : 0;
  if (res[1]!=0) res[1][56]=a1;
  a1=arg[1]? arg[1][58] : 0;
  if (res[1]!=0) res[1][57]=a1;
  a1=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][58]=a1;
  if (res[1]!=0) res[1][59]=a0;
  a1=arg[1]? arg[1][61] : 0;
  if (res[1]!=0) res[1][60]=a1;
  a1=arg[1]? arg[1][62] : 0;
  if (res[1]!=0) res[1][61]=a1;
  a1=arg[1]? arg[1][63] : 0;
  if (res[1]!=0) res[1][62]=a1;
  if (res[1]!=0) res[1][63]=a0;
  a1=arg[1]? arg[1][65] : 0;
  if (res[1]!=0) res[1][64]=a1;
  a1=arg[1]? arg[1][66] : 0;
  if (res[1]!=0) res[1][65]=a1;
  a1=arg[1]? arg[1][67] : 0;
  if (res[1]!=0) res[1][66]=a1;
  if (res[1]!=0) res[1][67]=a0;
  a1=arg[1]? arg[1][69] : 0;
  if (res[1]!=0) res[1][68]=a1;
  if (res[1]!=0) res[1][69]=a0;
  a1=arg[1]? arg[1][71] : 0;
  if (res[1]!=0) res[1][70]=a1;
  a1=arg[1]? arg[1][72] : 0;
  if (res[1]!=0) res[1][71]=a1;
  a1=arg[1]? arg[1][73] : 0;
  if (res[1]!=0) res[1][72]=a1;
  if (res[1]!=0) res[1][73]=a0;
  a1=arg[1]? arg[1][75] : 0;
  if (res[1]!=0) res[1][74]=a1;
  a1=arg[1]? arg[1][76] : 0;
  if (res[1]!=0) res[1][75]=a1;
  a1=arg[1]? arg[1][77] : 0;
  if (res[1]!=0) res[1][76]=a1;
  if (res[1]!=0) res[1][77]=a0;
  a1=arg[1]? arg[1][79] : 0;
  if (res[1]!=0) res[1][78]=a1;
  a1=arg[1]? arg[1][80] : 0;
  if (res[1]!=0) res[1][79]=a1;
  a1=arg[1]? arg[1][81] : 0;
  if (res[1]!=0) res[1][80]=a1;
  if (res[1]!=0) res[1][81]=a0;
  a1=arg[1]? arg[1][83] : 0;
  if (res[1]!=0) res[1][82]=a1;
  if (res[1]!=0) res[1][83]=a0;
  a1=arg[1]? arg[1][85] : 0;
  if (res[1]!=0) res[1][84]=a1;
  a1=arg[1]? arg[1][86] : 0;
  if (res[1]!=0) res[1][85]=a1;
  a1=arg[1]? arg[1][87] : 0;
  if (res[1]!=0) res[1][86]=a1;
  if (res[1]!=0) res[1][87]=a0;
  a1=arg[1]? arg[1][89] : 0;
  if (res[1]!=0) res[1][88]=a1;
  a1=arg[1]? arg[1][90] : 0;
  if (res[1]!=0) res[1][89]=a1;
  a1=arg[1]? arg[1][91] : 0;
  if (res[1]!=0) res[1][90]=a1;
  if (res[1]!=0) res[1][91]=a0;
  a1=arg[1]? arg[1][93] : 0;
  if (res[1]!=0) res[1][92]=a1;
  a1=arg[1]? arg[1][94] : 0;
  if (res[1]!=0) res[1][93]=a1;
  a1=arg[1]? arg[1][95] : 0;
  if (res[1]!=0) res[1][94]=a1;
  if (res[1]!=0) res[1][95]=a0;
  a1=arg[1]? arg[1][97] : 0;
  if (res[1]!=0) res[1][96]=a1;
  if (res[1]!=0) res[1][97]=a0;
  a1=arg[1]? arg[1][99] : 0;
  if (res[1]!=0) res[1][98]=a1;
  a1=arg[1]? arg[1][100] : 0;
  if (res[1]!=0) res[1][99]=a1;
  a1=arg[1]? arg[1][101] : 0;
  if (res[1]!=0) res[1][100]=a1;
  if (res[1]!=0) res[1][101]=a0;
  a1=arg[1]? arg[1][103] : 0;
  if (res[1]!=0) res[1][102]=a1;
  a1=arg[1]? arg[1][104] : 0;
  if (res[1]!=0) res[1][103]=a1;
  a1=arg[1]? arg[1][105] : 0;
  if (res[1]!=0) res[1][104]=a1;
  if (res[1]!=0) res[1][105]=a0;
  a1=arg[1]? arg[1][107] : 0;
  if (res[1]!=0) res[1][106]=a1;
  a1=arg[1]? arg[1][108] : 0;
  if (res[1]!=0) res[1][107]=a1;
  a1=arg[1]? arg[1][109] : 0;
  if (res[1]!=0) res[1][108]=a1;
  if (res[1]!=0) res[1][109]=a0;
  a1=arg[1]? arg[1][111] : 0;
  if (res[1]!=0) res[1][110]=a1;
  if (res[1]!=0) res[1][111]=a0;
  a1=arg[1]? arg[1][113] : 0;
  if (res[1]!=0) res[1][112]=a1;
  a1=arg[1]? arg[1][114] : 0;
  if (res[1]!=0) res[1][113]=a1;
  a1=arg[1]? arg[1][115] : 0;
  if (res[1]!=0) res[1][114]=a1;
  if (res[1]!=0) res[1][115]=a0;
  a1=arg[1]? arg[1][117] : 0;
  if (res[1]!=0) res[1][116]=a1;
  a1=arg[1]? arg[1][118] : 0;
  if (res[1]!=0) res[1][117]=a1;
  a1=arg[1]? arg[1][119] : 0;
  if (res[1]!=0) res[1][118]=a1;
  if (res[1]!=0) res[1][119]=a0;
  a1=arg[1]? arg[1][121] : 0;
  if (res[1]!=0) res[1][120]=a1;
  a1=arg[1]? arg[1][122] : 0;
  if (res[1]!=0) res[1][121]=a1;
  a1=arg[1]? arg[1][123] : 0;
  if (res[1]!=0) res[1][122]=a1;
  if (res[1]!=0) res[1][123]=a0;
  a1=arg[1]? arg[1][125] : 0;
  if (res[1]!=0) res[1][124]=a1;
  if (res[1]!=0) res[1][125]=a0;
  a1=arg[1]? arg[1][127] : 0;
  if (res[1]!=0) res[1][126]=a1;
  a1=arg[1]? arg[1][128] : 0;
  if (res[1]!=0) res[1][127]=a1;
  a1=arg[1]? arg[1][129] : 0;
  if (res[1]!=0) res[1][128]=a1;
  if (res[1]!=0) res[1][129]=a0;
  a1=arg[1]? arg[1][131] : 0;
  if (res[1]!=0) res[1][130]=a1;
  a1=arg[1]? arg[1][132] : 0;
  if (res[1]!=0) res[1][131]=a1;
  a1=arg[1]? arg[1][133] : 0;
  if (res[1]!=0) res[1][132]=a1;
  if (res[1]!=0) res[1][133]=a0;
  a1=arg[1]? arg[1][135] : 0;
  if (res[1]!=0) res[1][134]=a1;
  a1=arg[1]? arg[1][136] : 0;
  if (res[1]!=0) res[1][135]=a1;
  a1=arg[1]? arg[1][137] : 0;
  if (res[1]!=0) res[1][136]=a1;
  if (res[1]!=0) res[1][137]=a0;
  a1=arg[1]? arg[1][139] : 0;
  if (res[1]!=0) res[1][138]=a1;
  if (res[1]!=0) res[1][139]=a0;
  a1=arg[1]? arg[1][141] : 0;
  if (res[1]!=0) res[1][140]=a1;
  a1=arg[1]? arg[1][142] : 0;
  if (res[1]!=0) res[1][141]=a1;
  a1=arg[1]? arg[1][143] : 0;
  if (res[1]!=0) res[1][142]=a1;
  if (res[1]!=0) res[1][143]=a0;
  a1=arg[1]? arg[1][145] : 0;
  if (res[1]!=0) res[1][144]=a1;
  a1=arg[1]? arg[1][146] : 0;
  if (res[1]!=0) res[1][145]=a1;
  a1=arg[1]? arg[1][147] : 0;
  if (res[1]!=0) res[1][146]=a1;
  if (res[1]!=0) res[1][147]=a0;
  a1=arg[1]? arg[1][149] : 0;
  if (res[1]!=0) res[1][148]=a1;
  a1=arg[1]? arg[1][150] : 0;
  if (res[1]!=0) res[1][149]=a1;
  a1=arg[1]? arg[1][151] : 0;
  if (res[1]!=0) res[1][150]=a1;
  if (res[1]!=0) res[1][151]=a0;
  a1=arg[1]? arg[1][153] : 0;
  if (res[1]!=0) res[1][152]=a1;
  if (res[1]!=0) res[1][153]=a0;
  a1=arg[1]? arg[1][155] : 0;
  if (res[1]!=0) res[1][154]=a1;
  a1=arg[1]? arg[1][156] : 0;
  if (res[1]!=0) res[1][155]=a1;
  a1=arg[1]? arg[1][157] : 0;
  if (res[1]!=0) res[1][156]=a1;
  if (res[1]!=0) res[1][157]=a0;
  a1=arg[1]? arg[1][159] : 0;
  if (res[1]!=0) res[1][158]=a1;
  a1=arg[1]? arg[1][160] : 0;
  if (res[1]!=0) res[1][159]=a1;
  a1=arg[1]? arg[1][161] : 0;
  if (res[1]!=0) res[1][160]=a1;
  if (res[1]!=0) res[1][161]=a0;
  a1=arg[1]? arg[1][163] : 0;
  if (res[1]!=0) res[1][162]=a1;
  a1=arg[1]? arg[1][164] : 0;
  if (res[1]!=0) res[1][163]=a1;
  a1=arg[1]? arg[1][165] : 0;
  if (res[1]!=0) res[1][164]=a1;
  if (res[1]!=0) res[1][165]=a0;
  a1=arg[1]? arg[1][167] : 0;
  if (res[1]!=0) res[1][166]=a1;
  if (res[1]!=0) res[1][167]=a0;
  a1=arg[1]? arg[1][169] : 0;
  if (res[1]!=0) res[1][168]=a1;
  a1=arg[1]? arg[1][170] : 0;
  if (res[1]!=0) res[1][169]=a1;
  a1=arg[1]? arg[1][171] : 0;
  if (res[1]!=0) res[1][170]=a1;
  if (res[1]!=0) res[1][171]=a0;
  a1=arg[1]? arg[1][173] : 0;
  if (res[1]!=0) res[1][172]=a1;
  a1=arg[1]? arg[1][174] : 0;
  if (res[1]!=0) res[1][173]=a1;
  a1=arg[1]? arg[1][175] : 0;
  if (res[1]!=0) res[1][174]=a1;
  if (res[1]!=0) res[1][175]=a0;
  a1=arg[1]? arg[1][177] : 0;
  if (res[1]!=0) res[1][176]=a1;
  a1=arg[1]? arg[1][178] : 0;
  if (res[1]!=0) res[1][177]=a1;
  a1=arg[1]? arg[1][179] : 0;
  if (res[1]!=0) res[1][178]=a1;
  if (res[1]!=0) res[1][179]=a0;
  a1=arg[1]? arg[1][181] : 0;
  if (res[1]!=0) res[1][180]=a1;
  if (res[1]!=0) res[1][181]=a0;
  a1=arg[1]? arg[1][183] : 0;
  if (res[1]!=0) res[1][182]=a1;
  a1=arg[1]? arg[1][184] : 0;
  if (res[1]!=0) res[1][183]=a1;
  a1=arg[1]? arg[1][185] : 0;
  if (res[1]!=0) res[1][184]=a1;
  if (res[1]!=0) res[1][185]=a0;
  a1=arg[1]? arg[1][187] : 0;
  if (res[1]!=0) res[1][186]=a1;
  a1=arg[1]? arg[1][188] : 0;
  if (res[1]!=0) res[1][187]=a1;
  a1=arg[1]? arg[1][189] : 0;
  if (res[1]!=0) res[1][188]=a1;
  if (res[1]!=0) res[1][189]=a0;
  a1=arg[1]? arg[1][191] : 0;
  if (res[1]!=0) res[1][190]=a1;
  a1=arg[1]? arg[1][192] : 0;
  if (res[1]!=0) res[1][191]=a1;
  a1=arg[1]? arg[1][193] : 0;
  if (res[1]!=0) res[1][192]=a1;
  if (res[1]!=0) res[1][193]=a0;
  a1=arg[1]? arg[1][195] : 0;
  if (res[1]!=0) res[1][194]=a1;
  if (res[1]!=0) res[1][195]=a0;
  a1=arg[2]? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a1;
  a1=arg[2]? arg[2][2] : 0;
  if (res[2]!=0) res[2][1]=a1;
  a1=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][2]=a1;
  a1=1.;
  if (res[2]!=0) res[2][3]=a1;
  a2=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][4]=a2;
  a2=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][5]=a2;
  a2=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][6]=a2;
  if (res[2]!=0) res[2][7]=a0;
  a2=arg[2]? arg[2][9] : 0;
  if (res[2]!=0) res[2][8]=a2;
  a2=arg[2]? arg[2][10] : 0;
  if (res[2]!=0) res[2][9]=a2;
  a2=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][10]=a2;
  if (res[2]!=0) res[2][11]=a0;
  a2=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][12]=a2;
  if (res[2]!=0) res[2][13]=a0;
  a2=arg[2]? arg[2][15] : 0;
  if (res[2]!=0) res[2][14]=a2;
  a2=arg[2]? arg[2][16] : 0;
  if (res[2]!=0) res[2][15]=a2;
  a2=arg[2]? arg[2][17] : 0;
  if (res[2]!=0) res[2][16]=a2;
  if (res[2]!=0) res[2][17]=a0;
  a2=arg[2]? arg[2][19] : 0;
  if (res[2]!=0) res[2][18]=a2;
  a2=arg[2]? arg[2][20] : 0;
  if (res[2]!=0) res[2][19]=a2;
  a2=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][20]=a2;
  if (res[2]!=0) res[2][21]=a1;
  a2=arg[2]? arg[2][23] : 0;
  if (res[2]!=0) res[2][22]=a2;
  a2=arg[2]? arg[2][24] : 0;
  if (res[2]!=0) res[2][23]=a2;
  a2=arg[2]? arg[2][25] : 0;
  if (res[2]!=0) res[2][24]=a2;
  if (res[2]!=0) res[2][25]=a0;
  a2=arg[2]? arg[2][27] : 0;
  if (res[2]!=0) res[2][26]=a2;
  if (res[2]!=0) res[2][27]=a0;
  a2=arg[2]? arg[2][29] : 0;
  if (res[2]!=0) res[2][28]=a2;
  a2=arg[2]? arg[2][30] : 0;
  if (res[2]!=0) res[2][29]=a2;
  a2=arg[2]? arg[2][31] : 0;
  if (res[2]!=0) res[2][30]=a2;
  if (res[2]!=0) res[2][31]=a0;
  a2=arg[2]? arg[2][33] : 0;
  if (res[2]!=0) res[2][32]=a2;
  a2=arg[2]? arg[2][34] : 0;
  if (res[2]!=0) res[2][33]=a2;
  a2=arg[2]? arg[2][35] : 0;
  if (res[2]!=0) res[2][34]=a2;
  if (res[2]!=0) res[2][35]=a0;
  a2=arg[2]? arg[2][37] : 0;
  if (res[2]!=0) res[2][36]=a2;
  a2=arg[2]? arg[2][38] : 0;
  if (res[2]!=0) res[2][37]=a2;
  a2=arg[2]? arg[2][39] : 0;
  if (res[2]!=0) res[2][38]=a2;
  if (res[2]!=0) res[2][39]=a1;
  a2=arg[2]? arg[2][41] : 0;
  if (res[2]!=0) res[2][40]=a2;
  if (res[2]!=0) res[2][41]=a0;
  a2=arg[2]? arg[2][43] : 0;
  if (res[2]!=0) res[2][42]=a2;
  a2=arg[2]? arg[2][44] : 0;
  if (res[2]!=0) res[2][43]=a2;
  a2=arg[2]? arg[2][45] : 0;
  if (res[2]!=0) res[2][44]=a2;
  if (res[2]!=0) res[2][45]=a0;
  a2=arg[2]? arg[2][47] : 0;
  if (res[2]!=0) res[2][46]=a2;
  a2=arg[2]? arg[2][48] : 0;
  if (res[2]!=0) res[2][47]=a2;
  a2=arg[2]? arg[2][49] : 0;
  if (res[2]!=0) res[2][48]=a2;
  if (res[2]!=0) res[2][49]=a0;
  a2=arg[2]? arg[2][51] : 0;
  if (res[2]!=0) res[2][50]=a2;
  a2=arg[2]? arg[2][52] : 0;
  if (res[2]!=0) res[2][51]=a2;
  a2=arg[2]? arg[2][53] : 0;
  if (res[2]!=0) res[2][52]=a2;
  if (res[2]!=0) res[2][53]=a0;
  a0=arg[2]? arg[2][55] : 0;
  if (res[2]!=0) res[2][54]=a0;
  if (res[2]!=0) res[2][55]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void FBL_Quadcopter_ode_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FBL_Quadcopter_ode_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int FBL_Quadcopter_ode_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real FBL_Quadcopter_ode_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FBL_Quadcopter_ode_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FBL_Quadcopter_ode_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FBL_Quadcopter_ode_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FBL_Quadcopter_ode_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int FBL_Quadcopter_ode_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
