/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nmpc_flight_mode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* nmpc_flight_mode_expl_ode_fun:(i0[13],i1[4],i2[0])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16;
  /* #0: @0 = input[0][7] */
  w00 = arg[0] ? arg[0][7] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][8] */
  w00 = arg[0] ? arg[0][8] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #4: @0 = input[0][9] */
  w00 = arg[0] ? arg[0][9] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #6: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #7: @1 = input[0][10] */
  w01 = arg[0] ? arg[0][10] : 0;
  /* #8: @2 = input[0][4] */
  w02 = arg[0] ? arg[0][4] : 0;
  /* #9: @3 = (@1*@2) */
  w03  = (w01*w02);
  /* #10: @3 = (-@3) */
  w03 = (- w03 );
  /* #11: @4 = input[0][11] */
  w04 = arg[0] ? arg[0][11] : 0;
  /* #12: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][5] : 0;
  /* #13: @6 = (@4*@5) */
  w06  = (w04*w05);
  /* #14: @3 = (@3-@6) */
  w03 -= w06;
  /* #15: @6 = input[0][12] */
  w06 = arg[0] ? arg[0][12] : 0;
  /* #16: @7 = input[0][6] */
  w07 = arg[0] ? arg[0][6] : 0;
  /* #17: @8 = (@6*@7) */
  w08  = (w06*w07);
  /* #18: @3 = (@3-@8) */
  w03 -= w08;
  /* #19: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #20: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #21: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #22: @8 = (@1*@3) */
  w08  = (w01*w03);
  /* #23: @9 = (@6*@5) */
  w09  = (w06*w05);
  /* #24: @8 = (@8+@9) */
  w08 += w09;
  /* #25: @9 = (@4*@7) */
  w09  = (w04*w07);
  /* #26: @8 = (@8-@9) */
  w08 -= w09;
  /* #27: @8 = (@0*@8) */
  w08  = (w00*w08);
  /* #28: output[0][4] = @8 */
  if (res[0]) res[0][4] = w08;
  /* #29: @8 = (@4*@3) */
  w08  = (w04*w03);
  /* #30: @9 = (@6*@2) */
  w09  = (w06*w02);
  /* #31: @8 = (@8-@9) */
  w08 -= w09;
  /* #32: @9 = (@1*@7) */
  w09  = (w01*w07);
  /* #33: @8 = (@8+@9) */
  w08 += w09;
  /* #34: @8 = (@0*@8) */
  w08  = (w00*w08);
  /* #35: output[0][5] = @8 */
  if (res[0]) res[0][5] = w08;
  /* #36: @8 = (@6*@3) */
  w08  = (w06*w03);
  /* #37: @9 = (@4*@2) */
  w09  = (w04*w02);
  /* #38: @8 = (@8+@9) */
  w08 += w09;
  /* #39: @9 = (@1*@5) */
  w09  = (w01*w05);
  /* #40: @8 = (@8-@9) */
  w08 -= w09;
  /* #41: @0 = (@0*@8) */
  w00 *= w08;
  /* #42: output[0][6] = @0 */
  if (res[0]) res[0][6] = w00;
  /* #43: @0 = input[1][0] */
  w00 = arg[1] ? arg[1][0] : 0;
  /* #44: @8 = input[1][1] */
  w08 = arg[1] ? arg[1][1] : 0;
  /* #45: @9 = (@0+@8) */
  w09  = (w00+w08);
  /* #46: @10 = input[1][2] */
  w10 = arg[1] ? arg[1][2] : 0;
  /* #47: @9 = (@9+@10) */
  w09 += w10;
  /* #48: @11 = input[1][3] */
  w11 = arg[1] ? arg[1][3] : 0;
  /* #49: @9 = (@9+@11) */
  w09 += w11;
  /* #50: @12 = (2.*@9) */
  w12 = (2.* w09 );
  /* #51: @13 = 2 */
  w13 = 2.;
  /* #52: @12 = (@12/@13) */
  w12 /= w13;
  /* #53: @14 = (@5*@3) */
  w14  = (w05*w03);
  /* #54: @15 = (@7*@2) */
  w15  = (w07*w02);
  /* #55: @14 = (@14+@15) */
  w14 += w15;
  /* #56: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #57: output[0][7] = @14 */
  if (res[0]) res[0][7] = w14;
  /* #58: @14 = (@5*@7) */
  w14  = (w05*w07);
  /* #59: @15 = (@3*@2) */
  w15  = (w03*w02);
  /* #60: @14 = (@14-@15) */
  w14 -= w15;
  /* #61: @12 = (@12*@14) */
  w12 *= w14;
  /* #62: output[0][8] = @12 */
  if (res[0]) res[0][8] = w12;
  /* #63: @9 = (@9/@13) */
  w09 /= w13;
  /* #64: @3 = sq(@3) */
  w03 = casadi_sq( w03 );
  /* #65: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #66: @3 = (@3-@2) */
  w03 -= w02;
  /* #67: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #68: @3 = (@3-@5) */
  w03 -= w05;
  /* #69: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #70: @3 = (@3+@7) */
  w03 += w07;
  /* #71: @9 = (@9*@3) */
  w09 *= w03;
  /* #72: @3 = 9.8066 */
  w03 = 9.8065999999999995e+00;
  /* #73: @9 = (@9-@3) */
  w09 -= w03;
  /* #74: output[0][9] = @9 */
  if (res[0]) res[0][9] = w09;
  /* #75: @9 = 46.1681 */
  w09 = 4.6168051708217916e+01;
  /* #76: @3 = -0.174 */
  w03 = -1.7399999999999999e-01;
  /* #77: @3 = (@3*@0) */
  w03 *= w00;
  /* #78: @7 = 0.174 */
  w07 = 1.7399999999999999e-01;
  /* #79: @5 = (@7*@8) */
  w05  = (w07*w08);
  /* #80: @3 = (@3-@5) */
  w03 -= w05;
  /* #81: @2 = (@7*@10) */
  w02  = (w07*w10);
  /* #82: @3 = (@3+@2) */
  w03 += w02;
  /* #83: @13 = (@7*@11) */
  w13  = (w07*w11);
  /* #84: @3 = (@3+@13) */
  w03 += w13;
  /* #85: @12 = 0.04 */
  w12 = 4.0000000000000001e-02;
  /* #86: @14 = (@12*@4) */
  w14  = (w12*w04);
  /* #87: @14 = (@14*@6) */
  w14 *= w06;
  /* #88: @3 = (@3-@14) */
  w03 -= w14;
  /* #89: @14 = 0.02166 */
  w14 = 2.1659999999999999e-02;
  /* #90: @15 = (@14*@6) */
  w15  = (w14*w06);
  /* #91: @16 = (@15*@4) */
  w16  = (w15*w04);
  /* #92: @3 = (@3+@16) */
  w03 += w16;
  /* #93: @3 = (@9*@3) */
  w03  = (w09*w03);
  /* #94: output[0][10] = @3 */
  if (res[0]) res[0][10] = w03;
  /* #95: @7 = (@7*@0) */
  w07 *= w00;
  /* #96: @7 = (@7-@5) */
  w07 -= w05;
  /* #97: @7 = (@7-@2) */
  w07 -= w02;
  /* #98: @7 = (@7+@13) */
  w07 += w13;
  /* #99: @15 = (@15*@1) */
  w15 *= w01;
  /* #100: @7 = (@7-@15) */
  w07 -= w15;
  /* #101: @12 = (@12*@1) */
  w12 *= w01;
  /* #102: @12 = (@12*@6) */
  w12 *= w06;
  /* #103: @7 = (@7+@12) */
  w07 += w12;
  /* #104: @9 = (@9*@7) */
  w09 *= w07;
  /* #105: output[0][11] = @9 */
  if (res[0]) res[0][11] = w09;
  /* #106: @9 = 25 */
  w09 = 25.;
  /* #107: @7 = -8.06428e-05 */
  w07 = -8.0642800000000007e-05;
  /* #108: @7 = (@7*@0) */
  w07 *= w00;
  /* #109: @0 = 8.06428e-05 */
  w00 = 8.0642800000000007e-05;
  /* #110: @8 = (@0*@8) */
  w08  = (w00*w08);
  /* #111: @7 = (@7+@8) */
  w07 += w08;
  /* #112: @10 = (@0*@10) */
  w10  = (w00*w10);
  /* #113: @7 = (@7-@10) */
  w07 -= w10;
  /* #114: @0 = (@0*@11) */
  w00 *= w11;
  /* #115: @7 = (@7+@0) */
  w07 += w00;
  /* #116: @0 = (@14*@1) */
  w00  = (w14*w01);
  /* #117: @0 = (@0*@4) */
  w00 *= w04;
  /* #118: @7 = (@7-@0) */
  w07 -= w00;
  /* #119: @14 = (@14*@4) */
  w14 *= w04;
  /* #120: @14 = (@14*@1) */
  w14 *= w01;
  /* #121: @7 = (@7+@14) */
  w07 += w14;
  /* #122: @9 = (@9*@7) */
  w09 *= w07;
  /* #123: output[0][12] = @9 */
  if (res[0]) res[0][12] = w09;
  return 0;
}

CASADI_SYMBOL_EXPORT int nmpc_flight_mode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nmpc_flight_mode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nmpc_flight_mode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nmpc_flight_mode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nmpc_flight_mode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nmpc_flight_mode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nmpc_flight_mode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void nmpc_flight_mode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nmpc_flight_mode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int nmpc_flight_mode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nmpc_flight_mode_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nmpc_flight_mode_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nmpc_flight_mode_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nmpc_flight_mode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nmpc_flight_mode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nmpc_flight_mode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 17;
  return 0;
}

CASADI_SYMBOL_EXPORT int nmpc_flight_mode_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 17*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
